# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PythonProject\GUI\Addstudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import dataset_creator2 as dset
import training_set_opencv as tr

class Ui_Addstudent(object):
    def setupUi(self, Addstudent,MainWindow):
        Addstudent.setObjectName("MainWindow")
        Addstudent.resize(800, 550)
        Addstudent.setMaximumSize(QtCore.QSize(800, 550))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        Addstudent.setFont(font)
        Addstudent.setAutoFillBackground(False)
        Addstudent.setStyleSheet("background: qlineargradient(spread:pad, x1:0.14, y1:0.028, x2:1, y2:0.051, stop:0 rgba(37, 69, 198, 255), stop:1 rgba(21, 38, 111, 255));")
        self.centralwidget = QtWidgets.QWidget(Addstudent)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 115, 41, 31))
        self.label.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"font: 12pt \"Palatino Linotype\";\n"
"color: white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 158, 71, 51))
        self.label_2.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"font: 12pt \"Palatino Linotype\";\n"
"color: white")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 218, 141, 41))
        self.label_3.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
"font: 12pt \"Palatino Linotype\";\n"
"color: white")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 284, 81, 31))
        self.label_4.setStyleSheet("background-color: rgba(0,0,0,0%);\n"
                                   "font: 12pt \"Palatino Linotype\";\n"
                                   "color: white")
        self.label_4.setObjectName("label_4")
        self.idtext = QtWidgets.QTextEdit(self.centralwidget)
        self.idtext.setGeometry(QtCore.QRect(390, 110, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        self.idtext.setFont(font)
        self.idtext.setStyleSheet("background-color: rgb(255,255,255);\n"
"border: 2px solid #555;\n"
"border-radius: 10px;\n"
"border-style: outset;")
        self.idtext.setObjectName("textEdit")
        self.nametext = QtWidgets.QTextEdit(self.centralwidget)
        self.nametext.setGeometry(QtCore.QRect(390, 165, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        self.nametext.setFont(font)
        self.nametext.setStyleSheet("background-color: rgb(255,255,255);\n"
"border: 2px solid #555;\n"
"border-radius: 10px;\n"
"border-style: outset;")
        self.nametext.setObjectName("textEdit_2")
        self.rollnotext = QtWidgets.QTextEdit(self.centralwidget)
        self.rollnotext.setGeometry(QtCore.QRect(390, 220, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        self.rollnotext.setFont(font)
        self.rollnotext.setStyleSheet("background-color: rgb(255,255,255);\n"
"border: 2px solid #555;\n"
"border-radius: 10px;\n"
"border-style: outset;")
        self.rollnotext.setObjectName("textEdit_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(390, 280, 271, 41))
        '''font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        self.comboBox.setFont(font)'''
        self.comboBox.setStyleSheet("QComboBox {\n"
                                    "    font: 75 10pt \"Palatino Linotype\";\n"
                                    "    border: 1px solid gray;\n"
                                    "    border-top-left-radius: 10px;\n"
                                    "    border-bottom-left-radius: 10px;\n"
                                    "    min-width: 6em;\n"
                                    "    background-color:white;\n"
                                    "}\n"
                                    "\n"
                                    "QComboBox:on {\n"
                                    "    border-bottom-left-radius: 0px;\n"
                                    "    border-bottom-right-radius: 0px;\n"
                                    "}\n"
                                    "\n"
                                    "\n"
                                    "QComboBox::drop-down {\n"
                                    "\n"
                                    "    drop-down-color:white;\n"
                                    " \n"
                                    "}\n"
                                    "\n"
                                    "\n"
                                    "QComboBox QAbstractItemView {\n"
                                    "    border-bottom-right-radius: 0px;\n"
                                    "    border-bottom-left-radius: 0px;\n"
                                    "    background: white;\n"
                                    "    border: 1px solid gray;\n"
                                    "    box-shadow: transparent;\n"
                                    "}\n"
                                    "")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.addstubt = QtWidgets.QPushButton(self.centralwidget)
        self.addstubt.setGeometry(QtCore.QRect(300, 350, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.addstubt.setFont(font)
        self.addstubt.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-color: rgb(0,240,112);\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"     border-color: white;\n"
"     border-radius: 20px;\n"
"     color: white\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"color: black;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.addstubt.setObjectName("pushButton")
        self.donebt = QtWidgets.QPushButton(self.centralwidget)
        self.donebt.setGeometry(QtCore.QRect(320, 430, 131, 61))
        self.donebt.setMaximumSize(QtCore.QSize(800, 550))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.donebt.setFont(font)
        self.donebt.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-color: rgb(0,240,112);\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"     border-radius:2px;\n"
"     border-color: white;\n"
"border-radius: 20px;\n"
"color: white\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"color: black;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.donebt.setObjectName("pushButton_2")
        self.backbt = QtWidgets.QPushButton(self.centralwidget)
        self.backbt.setGeometry(QtCore.QRect(20, 20, 71, 41))
        self.backbt.setStyleSheet("QPushButton{\n"
"background-color: rgba(0,0,0,0%);\n"
"color: white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(0,0,0,30%);\n"
"color: white;\n"
"border: 0px solid;\n"
"border-style: outset;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-style: inset;\n"
"color: black;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"}")
        self.backbt.setObjectName("pushButton_3")
        self.backbt.clicked.connect(lambda:self.closeback(Addstudent,MainWindow))
        self.addstubt.clicked.connect(self.addscript)
        self.donebt.clicked.connect(lambda:self.trainscript(Addstudent,MainWindow))
        Addstudent.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Addstudent)
        self.statusbar.setObjectName("statusbar")
        Addstudent.setStatusBar(self.statusbar)

        self.retranslateUi(Addstudent)
        QtCore.QMetaObject.connectSlotsByName(Addstudent)

    def addscript(self):
        if self.idtext.toPlainText()=="" or self.nametext.toPlainText()=="" or self.rollnotext.toPlainText()=="" or self.comboBox.currentText()=="--Select Batch--":
            msg=QMessageBox()
            msg.setWindowTitle("Automated Attendance System")
            msg.setText("Please Enter All The Information Correctly")
            msg.exec()
        else:
            self.addstubt.setDisabled(True)
            self.donebt.setDisabled(True)
            dset.create(self.idtext.toPlainText(),self.nametext.toPlainText(),self.rollnotext.toPlainText(),self.comboBox.currentText()[-1])
            self.addstubt.setDisabled(False)
            self.donebt.setDisabled(False)
            self.idtext.clear()
            self.nametext.clear()
            self.rollnotext.clear()
            self.comboBox.setCurrentIndex(0)
            msg = QMessageBox()
            msg.setWindowTitle("Automated Attendance System")
            msg.setText("Added "+self.nametext.toPlainText()+" Successfully")
            msg.exec()

    def closeback(self,Addstudent,Mainwindow):
        Addstudent.hide()
        Mainwindow.show()

    def trainscript(self,window,Mainwindow):
        self.addstubt.setDisabled(True)
        self.donebt.setDisabled(True)
        tr.train()
        msg = QMessageBox()
        msg.setWindowTitle("Automated Attendance System")
        msg.setText("Model Trained Successfully")
        msg.exec()
        window.hide()
        Mainwindow.show()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Student"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "Roll Number"))
        self.addstubt.setText(_translate("MainWindow", "Add student"))
        self.label_4.setText(_translate("MainWindow", "Batch"))
        self.comboBox.setItemText(0, _translate("MainWindow", "--Select Batch--"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Batch 1"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Batch 2"))
        self.donebt.setText(_translate("MainWindow", "Done"))
        self.backbt.setText(_translate("MainWindow", "Back"))


def begin_addstudent():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Addstudent = QtWidgets.QMainWindow()
    ui = Ui_Addstudent()
    ui.setupUi(Addstudent)
    Addstudent.show()
    sys.exit(app.exec_())
