# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Addstudent import Ui_Addstudent
from TakeAttendance import Ui_TakeAttendance
from ViewExcel import Ui_ViewExcel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 550)
        MainWindow.setMaximumSize(QtCore.QSize(800, 550))
        MainWindow.setStyleSheet("background: qlineargradient(spread:pad, x1:0.14, y1:0.028, x2:1, y2:0.051, stop:0 rgba(37, 69, 198, 255), stop:1 rgba(21, 38, 111, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 250, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(0,0,0,0%)")
        self.label.setObjectName("label")
        self.addstubt = QtWidgets.QPushButton(self.centralwidget)
        self.addstubt.setGeometry(QtCore.QRect(60, 370, 171, 61))

        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addstubt.setFont(font)
        self.addstubt.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-color: rgb(0,240,112);\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"     border-radius:2px;\n"
"     border-color: white;\n"
"border-radius: 20px;\n"
"color: white\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"color: black;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.addstubt.setObjectName("pushButton")
        self.takeattbt = QtWidgets.QPushButton(self.centralwidget)
        self.takeattbt.setGeometry(QtCore.QRect(320, 370, 169, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.takeattbt.setFont(font)
        self.takeattbt.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-color: rgb(0,240,112);\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"     border-radius:2px;\n"
"     border-color: white;\n"
"border-radius: 20px;\n"
"color: white\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"color: black;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.takeattbt.setObjectName("pushButton_2")
        self.viewexbt = QtWidgets.QPushButton(self.centralwidget)
        self.viewexbt.setGeometry(QtCore.QRect(580, 370, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.viewexbt.setFont(font)
        self.viewexbt.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-color: rgb(0,240,112);\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"     border-radius:2px;\n"
"     border-color: white;\n"
"border-radius: 20px;\n"
"color: white\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"color: black;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.viewexbt.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 60, 191, 181))
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,0)")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Logo/Logo.png"))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #For Connecting Addstudent
        self.addstubt.clicked.connect(self.add_student)

        #For Connecting TakeAttendance
        self.takeattbt.clicked.connect(self.take_attendance)

        # For Connecting ViewExcel
        self.viewexbt.clicked.connect(self.view_excel)

    def view_excel(self):
        MainWindow.hide()
        self.ViewExcel = QtWidgets.QMainWindow()
        self.ui = Ui_ViewExcel()
        self.ui.setupUi(self.ViewExcel,MainWindow)
        self.ViewExcel.show()

    def take_attendance(self):
        MainWindow.hide()
        self.TakeAttendance = QtWidgets.QMainWindow()
        self.ui = Ui_TakeAttendance()
        self.ui.setupUi(self.TakeAttendance,MainWindow)
        self.TakeAttendance.show()

    def add_student(self):

        MainWindow.hide()
        self.AddStudent = QtWidgets.QMainWindow()
        self.ui = Ui_Addstudent()
        self.ui.setupUi(self.AddStudent,MainWindow)
        self.AddStudent.show()





    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automated Attendance System"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">                                          Automated Attendance System</p></body></html>"))
        self.addstubt.setText(_translate("MainWindow", "Add Student"))
        self.takeattbt.setText(_translate("MainWindow", "Take Attendance"))
        self.viewexbt.setText(_translate("MainWindow", "View Excel"))
import Logo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
