# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PythonProject\GUI\TakeAttendance.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import recognize_image_opencv as recog

class Ui_TakeAttendance(object):
    def setupUi(self,Take_attendance,mainwindow ):
        Take_attendance.setObjectName("MainWindow")
        Take_attendance.resize(800, 533)
        Take_attendance.setMaximumSize(QtCore.QSize(800, 550))
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.14, 0.028, 1.0, 0.051)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(37, 69, 198))
        gradient.setColorAt(1.0, QtGui.QColor(21, 38, 111))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.14, 0.028, 1.0, 0.051)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(37, 69, 198))
        gradient.setColorAt(1.0, QtGui.QColor(21, 38, 111))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.14, 0.028, 1.0, 0.051)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(37, 69, 198))
        gradient.setColorAt(1.0, QtGui.QColor(21, 38, 111))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.14, 0.028, 1.0, 0.051)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(37, 69, 198))
        gradient.setColorAt(1.0, QtGui.QColor(21, 38, 111))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.14, 0.028, 1.0, 0.051)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(37, 69, 198))
        gradient.setColorAt(1.0, QtGui.QColor(21, 38, 111))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.14, 0.028, 1.0, 0.051)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(37, 69, 198))
        gradient.setColorAt(1.0, QtGui.QColor(21, 38, 111))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.14, 0.028, 1.0, 0.051)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(37, 69, 198))
        gradient.setColorAt(1.0, QtGui.QColor(21, 38, 111))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.14, 0.028, 1.0, 0.051)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(37, 69, 198))
        gradient.setColorAt(1.0, QtGui.QColor(21, 38, 111))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.14, 0.028, 1.0, 0.051)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(37, 69, 198))
        gradient.setColorAt(1.0, QtGui.QColor(21, 38, 111))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Take_attendance.setPalette(palette)
        Take_attendance.setStyleSheet("background: qlineargradient(spread:pad, x1:0.14, y1:0.028, x2:1, y2:0.051, stop:0 rgba(37, 69, 198, 255), stop:1 rgba(21, 38, 111, 255));")
        self.centralwidget = QtWidgets.QWidget(Take_attendance)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox1.setGeometry(QtCore.QRect(380, 170, 271, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.comboBox1.setPalette(palette)
        '''font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.comboBox1.setFont(font)'''
        self.comboBox1.setStyleSheet("QComboBox {\n"
"    font: 75 12pt \"Palatino Linotype\";\n"
"    border: 2px solid gray;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    min-width: 6em;\n"
"    background-color:white;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    drop-down-color:white;\n"
"    drop-down-style:outset;\n"
"    drop-down: 2px solid gray;\n"
"   \n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-radius: 0px;\n"
"    border-radius: 0px;\n"
"    drop-down-color:white;\n"
"    background-color: white;\n"
"    border-style: outset;\n"
"    border: 2px solid gray;\n"
"    box-shadow: transparent;\n"
"    padding: 4px 4px 4px 4px;\n"
"    overflow:hidden\n"
" \n"
"}")
        self.comboBox1.setEditable(True)
        self.comboBox1.setDuplicatesEnabled(False)
        self.comboBox1.setFrame(True)
        self.comboBox1.setObjectName("comboBox1")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(170, 170, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color: rgb(255,255,255)")
        self.label1.setObjectName("label1")
        self.attendancebt = QtWidgets.QPushButton(self.centralwidget)
        self.attendancebt.setGeometry(QtCore.QRect(300, 310, 169, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.attendancebt.setFont(font)
        self.attendancebt.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-color: rgb(0,240,112);\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"     border-radius:2px;\n"
"     border-color: white;\n"
"border-radius: 20px;\n"
"color: white\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"color: black;\n"
"background-color:rgb(255,255,255);\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.attendancebt.setObjectName("pushButton")
        self.attbackbt = QtWidgets.QPushButton(self.centralwidget)
        self.attbackbt.setGeometry(QtCore.QRect(20, 20, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.attbackbt.setFont(font)
        self.attbackbt.setStyleSheet("QPushButton{\n"
"background-color: rgba(0,0,0,0%);\n"
"color: white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(0,0,0,30%);\n"
"color: white;\n"
"border: 0px solid;\n"
"border-style: outset;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-style: inset;\n"
"color: black;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"}")
        self.attbackbt.setObjectName("pushButton_3")
        Take_attendance.setCentralWidget(self.centralwidget)

        self.retranslateUi(Take_attendance)
        QtCore.QMetaObject.connectSlotsByName(Take_attendance)

        # For Back Button
        self.attbackbt.clicked.connect(lambda: self.closeatt(Take_attendance,mainwindow))

        self.attendancebt.clicked.connect(self.attscript)

    def attscript(self):
        if self.comboBox1.currentText() != "-- Select Subject --":
            self.attendancebt.setDisabled(True)
            recog.recognize(self.comboBox1.currentText())
            self.attendancebt.setDisabled(False)
            msg = QMessageBox()
            msg.setWindowTitle("Automated Attendance System")
            msg.setText("Attendances Marked Successfully")
            msg.exec()



    def closeatt(self, TakeAttendance,main):          #main is object of main gui i.e main.py
        TakeAttendance.hide()
        main.show()

    def retranslateUi(self, Take_attendance):
        _translate = QtCore.QCoreApplication.translate
        Take_attendance.setWindowTitle(_translate("MainWindow", "TakeAttendance"))
        self.comboBox1.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">-- Select Subject --</p></body></html>"))
        self.comboBox1.setCurrentText(_translate("MainWindow", "-- Select Subject --"))
        self.comboBox1.setItemText(0, _translate("MainWindow", "-- Select Subject --"))
        self.comboBox1.setItemText(1, _translate("MainWindow", "COA"))
        self.comboBox1.setItemText(2, _translate("MainWindow", "CNND"))
        self.comboBox1.setItemText(3, _translate("MainWindow", "OS"))
        self.comboBox1.setItemText(4, _translate("MainWindow", "AT"))
        self.comboBox1.setItemText(5, _translate("MainWindow", "Maths4"))
        self.comboBox1.setItemText(6, _translate("MainWindow", "Python"))
        self.comboBox1.setItemText(7, _translate("MainWindow", "MPL Lab B1"))
        self.comboBox1.setItemText(8, _translate("MainWindow", "MPL Lab B2"))
        self.comboBox1.setItemText(9, _translate("MainWindow", "NL Lab B1"))
        self.comboBox1.setItemText(10, _translate("MainWindow", "NL Lab B2"))
        self.comboBox1.setItemText(11, _translate("MainWindow", "Python Lab B1"))
        self.comboBox1.setItemText(12, _translate("MainWindow", "Python Lab B2"))
        self.comboBox1.setItemText(13, _translate("MainWindow", "Unix Lab B1"))
        self.comboBox1.setItemText(14, _translate("MainWindow", "Unix Lab B2"))
        self.label1.setText(_translate("MainWindow", "Enter Subject Name:"))
        self.attendancebt.setText(_translate("MainWindow", "Take Attendance"))
        self.attbackbt.setText(_translate("MainWindow", "Back"))
