# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PythonProject\GUI\ViewExcel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import webbrowser
import Cumulative_lab
import Cumulative

from PyQt5.QtWidgets import QMessageBox


class Ui_ViewExcel(object):
    def setupUi(self, View_Excel, main):
        View_Excel.setObjectName("MainWindow")
        View_Excel.resize(800, 550)
        View_Excel.setMaximumSize(QtCore.QSize(800, 550))
        View_Excel.setStyleSheet("background: qlineargradient(spread:pad, x1:0.14, y1:0.028, x2:1, y2:0.051, stop:0 rgba(37, 69, 198, 255), stop:1 rgba(21, 38, 111, 255));")
        self.centralwidget = QtWidgets.QWidget(View_Excel)
        self.centralwidget.setObjectName("centralwidget")
        self.deflistbt = QtWidgets.QPushButton(self.centralwidget)
        self.deflistbt.setGeometry(QtCore.QRect(290, 370, 220, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.deflistbt.setFont(font)
        self.deflistbt.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-color: rgb(0,240,112);\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"     border-radius:2px;\n"
"     border-color: white;\n"
"border-radius: 20px;\n"
"color: white\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"color: black;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.deflistbt.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 200, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgba(0,0,0,0%);")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(390, 200, 191, 41))
        '''font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        self.comboBox.setFont(font)'''
        self.comboBox.setStyleSheet("QComboBox {\n"
"    font: 75 12pt \"Palatino Linotype\";\n"
"    border: 2px solid gray;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    min-width: 6em;\n"
"    background-color:white;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down {\n"
"\n"
"    drop-down-color:white;\n"
" \n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    background: white;\n"
"    border: 2px solid gray;\n"
"    box-shadow: transparent;\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.exbackbt = QtWidgets.QPushButton(self.centralwidget)
        self.exbackbt.setGeometry(QtCore.QRect(20, 20, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exbackbt.setFont(font)
        self.exbackbt.setStyleSheet("QPushButton{\n"
"background-color: rgba(0,0,0,0%);\n"
"color: white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(0,0,0,30%);\n"
"color: white;\n"
"border: 0px solid;\n"
"border-style: outset;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" border-style: inset;\n"
"color: black;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"}")
        self.exbackbt.setObjectName("pushButton_2")
        self.excelbt = QtWidgets.QPushButton(self.centralwidget)
        self.excelbt.setGeometry(QtCore.QRect(40, 370, 220, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.excelbt.setFont(font)
        self.excelbt.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-color: rgb(0,240,112);\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"     border-radius:2px;\n"
"     border-color: white;\n"
"border-radius: 20px;\n"
"color: white\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"color: black;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.excelbt.setObjectName("pushButton_3")
        View_Excel.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(View_Excel)
        self.statusbar.setObjectName("statusbar")
        View_Excel.setStatusBar(self.statusbar)

        self.marksbt = QtWidgets.QPushButton(self.centralwidget)
        self.marksbt.setGeometry(QtCore.QRect(540, 370, 220, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.marksbt.setFont(font)
        self.marksbt.setStyleSheet("QPushButton {\n"
                                   "    color: #333;\n"
                                   "    border: 2px solid #555;\n"
                                   "    border-radius: 20px;\n"
                                   "    border-style: outset;\n"
                                   "    background-color: rgb(0,240,112);\n"
                                   "    padding: 5px;\n"
                                   "    }\n"
                                   "\n"
                                   "QPushButton:hover {\n"
                                   "     border-radius:2px;\n"
                                   "     border-color: white;\n"
                                   "border-radius: 20px;\n"
                                   "color: white\n"
                                   "    }\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "    border-style: inset;\n"
                                   "color: black;\n"
                                   "    background: qradialgradient(\n"
                                   "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                   "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
                                   "        );\n"
                                   "    }")
        self.marksbt.setObjectName("pushButton_4")
        self.retranslateUi(View_Excel)
        QtCore.QMetaObject.connectSlotsByName(View_Excel)

        # For Back Button
        self.exbackbt.clicked.connect(lambda: self.closeexcel(View_Excel, main))
        # For View Excel
        self.excelbt.clicked.connect(self.openfolder)

        #For Defaulter's Attendance
        self.deflistbt.clicked.connect(self.deflist)

        # For Defaulter's Attendance
        self.marksbt.clicked.connect(self.attmarks)


    def closeexcel(self, Excel, main):               #main is object of main gui i.e main.py
        Excel.hide()
        main.show()

    def openfolder(self):
        if os.path.exists('./Attendance/'+self.comboBox.currentText()):
           webbrowser.open(os.path.dirname(os.path.realpath(__file__))+".//Attendance//"+self.comboBox.currentText())

    def deflist(self):
        if self.comboBox.currentText() != "-- Select Subject --":
            subject = self.comboBox.currentText()
            if subject[-2:] == "B1" or subject[-2:] == "B2":
                val = Cumulative_lab.listdefaulter(subject)
            else:
                val = Cumulative.listdefaulter(subject)
            msg = QMessageBox()
            msg.setWindowTitle("Automated Attendance System")
            if val == -1:
                msg.setText("Defaulter's List Already Created ")
            else:
                msg.setText("Defaulter's List Is Created")
            msg.exec_()

    def attmarks(self):
        if self.comboBox.currentText() != "-- Select Subject --":
            subject = self.comboBox.currentText()
            if subject[-2:] == "B1" or subject[-2:] == "B2":
                val = Cumulative_lab.markscalci(subject)
            else:
                val = Cumulative.markscalc(subject)
            msg = QMessageBox()
            msg.setWindowTitle("Automated Attendance System")
            if val == -1:
                msg.setText("Marks List Already Created ")
            else:
                msg.setText("Marks List Is Created")
            msg.exec_()


    def retranslateUi(self, View_Excel):
        _translate = QtCore.QCoreApplication.translate
        View_Excel.setWindowTitle(_translate("MainWindow", "View Attendance"))
        self.deflistbt.setText(_translate("MainWindow", "Defaulter's List"))
        self.label.setText(_translate("MainWindow", "Enter Subject Name"))
        self.comboBox.setItemText(0, _translate("MainWindow", "-- Select Subject --"))
        self.comboBox.setItemText(1, _translate("MainWindow", "COA"))
        self.comboBox.setItemText(2, _translate("MainWindow", "CNND"))
        self.comboBox.setItemText(3, _translate("MainWindow", "OS"))
        self.comboBox.setItemText(4, _translate("MainWindow", "AT"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Maths4"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Python"))
        self.comboBox.setItemText(7, _translate("MainWindow", "MPL Lab B1"))
        self.comboBox.setItemText(8, _translate("MainWindow", "MPL Lab B2"))
        self.comboBox.setItemText(9, _translate("MainWindow", "NL Lab B1"))
        self.comboBox.setItemText(10, _translate("MainWindow", "NL Lab B2"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Python Lab B1"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Python Lab B2"))
        self.comboBox.setItemText(13, _translate("MainWindow", "Unix Lab B1"))
        self.comboBox.setItemText(14, _translate("MainWindow", "Unix Lab B2"))
        self.exbackbt.setText(_translate("MainWindow", "Back"))
        self.excelbt.setText(_translate("MainWindow", "View Excel"))
        self.marksbt.setText(_translate("MainWindow", "Attendance Marks"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewExcel = QtWidgets.QMainWindow()
    ui = Ui_ViewExcel()
    ui.setupUi(ViewExcel)
    ViewExcel.show()
    sys.exit(app.exec_())
